# Generated by Django 3.2.9 on 2021-11-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_apps_app'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='LoginFunc',
        ),
    ]
