# Generated by Django 3.2.9 on 2021-11-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_login_loginfunc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatario',
            name='complemento',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
