# Generated by Django 3.2.9 on 2021-11-26 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20211125_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatario',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='donatario',
            old_name='Estado',
            new_name='estado',
        ),
    ]
