# Generated by Django 3.2.9 on 2021-11-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20211126_0514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donatario',
            new_name='LoginDonat',
        ),
    ]
