# Generated by Django 3.2.9 on 2021-11-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_donatario_logindonat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doador',
            new_name='LoginDoador',
        ),
        migrations.AlterField(
            model_name='logindonat',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindonat',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
