# Generated by Django 3.2.9 on 2021-11-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20211126_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logindoador',
            old_name='Bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='logindoador',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.AlterField(
            model_name='logindoador',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='logindoador',
            name='telefone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
